
 
## Assignment 1
#### Course: Introduction to Data Science (DAT540)
#### Topic: Basic Python
#### Name: Aleksander B. Jakobsen
#### Stundent number: 236227
#### University of Stavanger
#### September 2020


***
*Note: Relevant sources are given as comment in code, and all sources displayed in the end of the notebook.*
***
### Problem 1: Rock-Paper-Siccor
For problem 1, two functions have been defined. The first one is used to prompt players for input. This function, called getUserInputs(), presents the choices to the players. The function further takes input arguments from the users, first from player 1, and then from player 2. For each given input, a while loop is used to re-prompt for input if the given input is unvalid. Valid inputs are pre-defined in the function. The function returns two variables; the choices of player 1 and player 2. 

getUserInputs() is defined as: 

In [1]:
#Prompt for player inputs
def getUserInputs():
    """
    Asks player number 1 and player number 2 for choice. 
    Only valid choices (rock, paper, siccor) are accepted.
    Returns the choice of player 1 and player 2
    """
    validInputs = ['rock','paper','siccor']
    print("Welcome to rock-paper-scissor!\nThe possible choices are:\n-rock \n-paper \n-siccor ")
    player1 = input("Player 1, please enter your choice (rock, paper or siccor): ").lower() #Lower so that is input is given in capital letters, it is accepted. 
    #Check for valid input player 1
    while(player1 not in validInputs):
        player1 = input("Unvalid input. Player 1, please re-enter your choice (rock, paper or siccor):").lower()
    player2 = input("Player 2, please enter your choice (rock, paper or siccor): ").lower()
    #Check for valid input player 2
    while(player2 not in validInputs):
        player2 = input("Unvalid input. Player 2, please re-enter your choice (rock, paper or siccor):").lower()
    return player1, player2

The second function defined for problem 1 is the game itself, called RoPaSc(). This function defines a list playerHands consisting of the user inputs, as well as an arbitrary "index0" element. Thus, in the list playerHands, the choice of player 1 is stored with index 1, and the choice of player 2 is stored with index 2.

Further, the player choices are printed to acheive the output form as defined in the problem sheet.

The function checks if the players have played the same hand. If this is the case, then the players are informed and nobody wins. Otherwise, the function checks the hands of the players and returns the winner. 

The function is defined as: 

In [2]:
#Define the game
def RoPaSc(player_1_hand, player_2_hand):
    """
    player_1_hand: Player 1 input in string format
    player_2_hand: Player 2 input in string format
    The function prints who won the game, or if it is a tie.
    """
    playerHands = ["index0",player_1_hand,player_2_hand] #Index0 so that player 1 is index 1 and player 2 is index 2
    print("Player 1: " + player_1_hand +"\nPlayer 2: " + player_2_hand)
    if (player_1_hand == player_2_hand):
        output = "None of you won, you played the same hands!"
    elif ((player_1_hand == "rock" or player_2_hand == "rock") and (player_1_hand == "siccor" or player_2_hand == "siccor")):
        #rock beats sciccor
        output = "Player " + str([r for r in range(len(playerHands)) if playerHands[r] == "rock"]) + ": wins."
    elif ((player_1_hand == "paper" or player_2_hand == "paper") and (player_1_hand == "rock" or player_2_hand == "rock")):
        #paper beats rock
        output = "Player " + str([p for p in range(0,len(playerHands)) if playerHands[p] == "paper"]) + ": wins."
    elif ((player_1_hand == "paper" or player_2_hand == "paper") and (player_1_hand == "siccor" or player_2_hand == "siccor")):
        #siccor beats paper
        output = "Player " + str([s for s in range(len(playerHands)) if playerHands[s] == "siccor"]) + ": wins."
    output = output.replace("[","")
    output = output.replace("]","")
    print(output)

Now lets try to play the game! 

In [3]:
#Get the inputs from the users:
player1, player2 = getUserInputs() #Try for example with rock and siccor


#Run the game using inputs:
RoPaSc(player1,player2)

Welcome to rock-paper-scissor!
The possible choices are:
-rock 
-paper 
-siccor 
Player 1, please enter your choice (rock, paper or siccor): rock
Player 2, please enter your choice (rock, paper or siccor): siccor
Player 1: rock
Player 2: siccor
Player 1: wins.


***
### Problem 2: Ceaser cipher
For the Ceaser cipher problem, I define several functions. Firstly, I define a function to open the file, openFile(someFile): 

In [4]:
def openFile(someFile):
    """
    someFile: Name of a txt file as a string
    openFile opens the specified .txt file and returns the content of the file.
    """
    f = open(someFile,"r")
    return f.read()

Lets quickly check that this works as desired: 

In [5]:
print(openFile("plain.txt"))

Why is AI attracting so much attention?
AI is the new electricity. It will transform every industry and create huge economic value. 
Technology like supervised learning is automation on steroids. 
It is very good at automating tasks and will have an impact on every sector from healthcare to manufacturing, logistics and retail.


This looks good. Note that for this to work, the file plain.txt needs to be in the same folder location (working directory) as the current notebook. 

The next step is to cipher the text. The cipher key, k, is specified to be the last number of the year of a date of birth. 
Example: Date of birth is 01-10-1996, then k = 6. 

To start off,  some user input is needed to get a birthdate. This is done by defining a function getDateOfBirth(), as shown below: 

In [6]:
def getDateOfBirth():
    """
    prompts user for birthday.
    returns the given birthday.
    """
    date = input("Enter your date of birth [DD-MM-YYYY]: ")
    return date

In order to assure that the input is valid, a function named checkValid(date) is defined. This function calls several other functions which I also define: 

In [7]:
def checkValid(date):
    """
    Raises error if date is unvalid.
    Returns date if valid.
    """
    d, m, y = d,m,y = date.split("-")
    try: 
        year = checkYear(y)
        month = checkMonth(m)
        day = checkDay(d)
    except ValueError as err:
        print("Birthday not valid date: " + str(err))
    return date


Where the functions checkYear(y), checkMonth(m) and checkDay(d) is defined as the following: 

In [8]:

def checkYear(year):
    """
    Checks if the input year is valid.
    Raises ValueError if nonvalid year. 
    Returns year if valid. 
    """
    yr = int(year)
    if (yr > 1900 and yr <= 2020):
        return yr
    else:
        raise ValueError("Year not valid")

def checkMonth(month):
    """
    Checks if the input month is valid.
    Raises ValueError if nonvalid month. 
    Returns month if valid. 
    """
    m = int(month)
    if (m >= 1 and m <= 12):
        return m
    else:
        raise ValueError("Month not valid")

def checkDay(day):
    """
    Checks if the input day is valid.
    Raises ValueError if nonvalid day. 
    Returns day if valid. 
    """
    d = int(day)
    if (d >=1 and d <=31):
        return d
    else:
        raise ValueError("Day not valid")


To get the key from the date, I define a function which takes the date as input (string format), and returns the key, k, as an int: 

In [9]:
def getK(date):
    """
    date: Birthday as a string [DD-MM-YYYY]
    k: Year ending of birthday
    returns k
    """
    d,m,y = date.split("-")
    k = y[-1]
    return int(k)

Lets try combining some of the above code and see if it works. First by giving a valid date as input, and then by giving unvalid input. 

In [10]:
day = getDateOfBirth() #Try by giving valid date, for example "01-01-1996"
validDate = checkValid(day)
k = getK(day)
print("Key: ",k)

Enter your date of birth [DD-MM-YYYY]: 01-01-1996
Key:  6


In [11]:
day = getDateOfBirth() #Try by giving date for example "01-01-1889"
validDate = checkValid(day)
k = getK(day)


Enter your date of birth [DD-MM-YYYY]: 01-01-1889
Birthday not valid date: Year not valid


As seen in the two code segments above, when giving a non-valid input, a message stating what is unvalid is given. 

In order to cipher the text, I convert the imported .txt file to an array by defining a function stringToList(someString) which takes a string as an argument and returns an array of characters. For this, numpy is needed: 

In [12]:
import numpy as np

def stringToList(someString):
    """
    Returns string as array of characters
    """
    return np.asarray([char for char in someString])


Combining all the above as well as defining rules for the cipher results in the cipered text. 

In [13]:

def ceaserCipher(fileName):
    """
    Prompts user for a birthday.
    Returns content of given .txt file ciphered using the ceaser cipher method.
    Note: Does not cipher symbols, e.g. "!",".","?".
    """
    fileContent = openFile(fileName) #Open file content
    contentAsChar = stringToList(fileContent) #Convert content to chars
    birth = getDateOfBirth() #Get date of birth from user
    isValid = checkValid(birth) #Check if valid date is given
    k = getK(birth)
    cipherString = ""
    for c in contentAsChar:
        if c.isalpha(): #check if c is ASCII alphanumerical character. #Source [1]
            cipher = (ord(c) + k) #Source[2]
            if cipher > ord('z'):
                cipher -= 26 #shift if outside alphabet
        else: #if c is not a alphabetical char (ex: "?", ".", "!" etc.)
            cipher = ord(c)
        cipherString += chr(cipher)
    print("Plain text: " + fileContent)
    return "\nCiphered text: " + cipherString

What exatcly is happening in the ceaserCipher(fileName) function above?
To start of, the funtion retrieves the content of the file, using the already defined openFile(fileName) function. Then, the content of the file is converted to an array of charachters using the strinToList(fileContent) function. The user is then asked to give date of birth, and this date is checked. The getK(birth) function is used to retrieve the cipher key. 

With the retrieved key, the cipher itself can begin. An empty string called cipherString is created. I then loop through the characters. For each character, I use the isalpha() function to check if the character is alphanumerical. In this way, I avoid shifting any symboks like "!",".","?" and so on. 

If the character is alphanumerical, I convert the caracter to its ASCIInumerical value, using the ord() function. I then add the key. I check that the new value is not outside the alphabet (this is done by ``` 
if cipher > ord('z'): ``` in line 17 in the above code). If the new value is outside the alphabet, I "wrap" it around the alphabet by substracting the length of the alphabet. Then, this is the new character value.

If the character is not alphanumerical, it is simply added as it is. 
Finally, the characters are combined to a string. 

Lets try the function!

In [14]:
print(ceaserCipher("plain.txt")) #Try to cipher with something, say 02-02-2001, then its easy to recognize

Enter your date of birth [DD-MM-YYYY]: 02-02-2001
Plain text: Why is AI attracting so much attention?
AI is the new electricity. It will transform every industry and create huge economic value. 
Technology like supervised learning is automation on steroids. 
It is very good at automating tasks and will have an impact on every sector from healthcare to manufacturing, logistics and retail.

Ciphered text: Xiz jt BJ buusbdujoh tp nvdi buufoujpo?
BJ jt uif ofx fmfdusjdjuz. Ju xjmm usbotgpsn fwfsz joevtusz boe dsfbuf ivhf fdpopnjd wbmvf. 
Ufdiopmphz mjlf tvqfswjtfe mfbsojoh jt bvupnbujpo po tufspjet. 
Ju jt wfsz hppe bu bvupnbujoh ubtlt boe xjmm ibwf bo jnqbdu po fwfsz tfdups gspn ifbmuidbsf up nbovgbduvsjoh, mphjtujdt boe sfubjm.


*** 
### Problem 3: Find most consecutive ones in ndarray (two-dimensions)

To start off, I define a function, checkOnesArrar(someArray) which takes a one-dimensional array, someArray as input and returns the max number of consecutive ones in that array. 

To do this, I use use the groupby function from itertools. 
The groupby function groups consecutive elements if they are identical. The groupby function retruns tuples containing the element key and the sequence of elements itself. 

Quick example of what the groupby function does: 

In [15]:
from itertools import groupby #Source [3] 
ar = np.array([1,1,1,0,0,1,1,1,1])
tuples = groupby(ar)
for t,g in tuples:
    print(t, list(g))

1 [1, 1, 1]
0 [0, 0]
1 [1, 1, 1, 1]


So the output is value of the groupes, as well as the group itself. 
Then, by simply using the max length of ones in each group, I find the longest consecutive lines of ones. The complete function is as defined below: 

In [16]:
def checkOnesArray(someArray):
    tuples = groupby(someArray)
    numberOfConsecutives = []
    for t in tuples:
        if t[0] == 1:
            numberOfConsecutives.append(len(list(t[1])))
    if len(numberOfConsecutives) == True: 
        maxOnes = max(numberOfConsecutives)         
        return maxOnes
    else: #In case of only zeroes
        return 0

If the complete function above, note that I have implemented in line 5 an if statement ```if t[0] == 1:```. This way, I state that I'm only interested in the groups where there are ones, and that I'm not interested in zeros. Also not that in line 10, the else statement is implemented to avoid errors if a given array only consists of zeros. For example if the input would have been \[0,0,0,0], then there are no consecutive ones, and the function should then return 0. 

I start off by defining a function, createArray(), that allows the user to create an array: 

In [17]:
def createArray():
    print("Hello! Let's generate a N x M matrix consisting of zeros and ones!")
    n = int(input("Enter N: "))
    m = int(input("Enter M: "))
    arr2d = np.random.randint(low = 0, high = 2, size = (n,m)) #high = 2 as stated in source [4] https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
    return arr2d

arr2d = createArray()
print(arr2d)

Hello! Let's generate a N x M matrix consisting of zeros and ones!
Enter N: 2
Enter M: 3
[[1 0 1]
 [1 1 0]]


We now have an ndarray of two dimensions (matrix) which contains zeros and ones. 

I first start off creating a function checkHorisontal(twoDimArr). The function takes a two dimensional array as input. It loops throug each row. Each row is send to the checkOnesArray(someArray) function. Each check returns a number of consecutive ones. In line 5, ```if ones > maxOnesHor:``` and line 6 ```maxOnesHor = ones```, the maximum ones is stored. This value is then returned. 

In [18]:
def checkHorisontal(twoDimArr):
    maxOnesHor = 0
    for row in twoDimArr:
        ones = checkOnesArray(row)
        if ones > maxOnesHor:
            maxOnesHor = ones
    return maxOnesHor


Lets quickly test this on the array given above:

In [19]:
print(arr2d)
print("Maximum consecutive ones in the horisontal direction:",checkHorisontal(arr2d)) 

[[1 0 1]
 [1 1 0]]
Maximum consecutive ones in the horisontal direction: 2


By transposing the two-dimensional array, one can check the consecutive ones in the vertical direction by using the checkHorisontal(twoDimArray) function: 

In [20]:
def checkVertical(twoDimArr):
    transposed = twoDimArr.T #Using the transposed matrix to check vertical in the same way as horisontal
    maxOnesVert = checkHorisontal(transposed)
    return maxOnesVert

Lets test this as well: 

In [21]:
print(arr2d)
print("Maximum consecutive ones in the vertical direction:",checkVertical(arr2d))

[[1 0 1]
 [1 1 0]]
Maximum consecutive ones in the vertical direction: 2


Further, a function to extract the diagonals from the two-dimensional array is defined. The function uses the numpy.diagonal() to extract diagonals. Looping for various offsets allows for extracing all the diagonals. The funcction returns a list of arrays containing the diagonals.

In [22]:
def getDiagonals(twoDimArr):
    n, m = np.shape(twoDimArr)
    off = max(n,m)
    diags = []
    #print(n, m, "Largest: ", off)
    for o in range(-off,off):
        diag = (twoDimArr.diagonal(offset = o)) #Source [5]
        if diag.size != 0:
            diags.append(diag)
    return diags

Lets see how this looks:

In [23]:
print(arr2d)
diags = getDiagonals(arr2d)
print("Diagonals as numpy arrays:",diags)

[[1 0 1]
 [1 1 0]]
Diagonals as numpy arrays: [array([1]), array([1, 1]), array([0, 0]), array([1])]


The diagonals are used as input in a checkDiagonals(someDiags) function, which is simular to the checkHorizontal(twoDimArr) function:

In [24]:
def checkDiagonals(someDiags):
    maxOnesDiag = 0
    for d in someDiags:
        ones = checkOnesArray(d)
        if ones > maxOnesDiag:
            maxOnesDiag = ones
    return maxOnesDiag

Lets test this:

In [25]:
print(arr2d)
print("Maximum consecutive ones in the diagonals:",checkDiagonals(diags))

[[1 0 1]
 [1 1 0]]
Maximum consecutive ones in the diagonals: 2


For the anti-diagonals, the matrix can simply be flipped using numpy.fliplr(). A function, getAntiDiagonals(twoDimArr), is created to flip the matrix. In the function, the flipped matrix is used as input to the getDiagonals(twoDimArr) to retrieve the diagonals of the flipped matrix: 

In [26]:
def getAntiDiagonals(twoDimArr):
    flipped = np.fliplr(twoDimArr)
    flippedDiags = getDiagonals(flipped)
    return flippedDiags


Lets check this:

In [27]:
print(arr2d)
print("Anti-diagonals as numpy array:",getAntiDiagonals(arr2d))

[[1 0 1]
 [1 1 0]]
Anti-diagonals as numpy array: [array([0]), array([1, 1]), array([0, 1]), array([1])]


To check for consecutive ones in the anti-diagonals, a function checkAntiDiagonals(twoDimArr) is defined. The function combines the getAntiDiagonals(twoDimArr) function and the checkDiagonals(someDiags) function:

In [28]:
def checkAntiDiagonals(twoDimArr):
    someAntiDiags = getAntiDiagonals(twoDimArr)
    maxOnesAntiDiag = checkDiagonals(someAntiDiags)
    return maxOnesAntiDiag

Lets test this: 

In [29]:
print(arr2d)
print("Maximum consecutive ones in the anti-diagonal:",checkAntiDiagonals(arr2d))

[[1 0 1]
 [1 1 0]]
Maximum consecutive ones in the anti-diagonal: 2


Now I combine all of this together into one function: 

In [30]:
def maxNumberOfOnes(twoDimArray):
    maxHorisontal = checkHorisontal(twoDimArray)
    maxVertical = checkVertical(twoDimArray)
    diagonals = getDiagonals(twoDimArray)
    maxDiagonals = checkDiagonals(diagonals)
    maxAntiDiagonals = checkAntiDiagonals(twoDimArray)
    print("Max consecutive horisontal: ",maxHorisontal)
    print("Max consecutive vertical: ",maxVertical)
    print("Max consecutive diagonal: ",maxDiagonals)
    print("Max consecutive anti-diagonal: ",maxAntiDiagonals)
    ones = max(maxHorisontal, maxVertical, maxDiagonals, maxAntiDiagonals)
    return "Max consecutive: " + str(ones)

And lets try it together with the input function:

In [31]:
userArray = createArray() #Try for example 3 and 4
print(userArray)
maxNumberOfOnes(userArray)

Hello! Let's generate a N x M matrix consisting of zeros and ones!
Enter N: 3
Enter M: 4
[[0 0 1 1]
 [1 0 1 1]
 [1 0 1 0]]
Max consecutive horisontal:  2
Max consecutive vertical:  3
Max consecutive diagonal:  2
Max consecutive anti-diagonal:  2


'Max consecutive: 3'

And we see that this works well. Lets test for some other sizes just to be sure: 

In [32]:
userOtherArray = createArray() #Try for example 6 and 3
print(userOtherArray)
print(maxNumberOfOnes(userOtherArray))

Hello! Let's generate a N x M matrix consisting of zeros and ones!
Enter N: 6
Enter M: 3
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [1 1 0]
 [0 1 1]]
Max consecutive horisontal:  3
Max consecutive vertical:  0
Max consecutive diagonal:  3
Max consecutive anti-diagonal:  2
Max consecutive: 3


In [34]:
userAnotherArray = createArray() #Try for example 2 and 5
print(userAnotherArray)
print(maxNumberOfOnes(userAnotherArray))

Hello! Let's generate a N x M matrix consisting of zeros and ones!
Enter N: 2
Enter M: 5
[[0 0 0 1 1]
 [0 0 0 0 1]]
Max consecutive horisontal:  2
Max consecutive vertical:  2
Max consecutive diagonal:  2
Max consecutive anti-diagonal:  1
Max consecutive: 2


*** 
### Sources

1. *Built-in Types*, The Python Standard Library. Accessed 17.09.2020 \[online]. Available at: https://docs.python.org/3/library/stdtypes.html
2. *Python ord(), Programiz.com. Accessed 18.09.2020 \[online]. Available at: https://www.programiz.com/python-programming/methods/built-in/ord
3. *itertools.groupby() in Python*, geeksforgeeeks.org, 30-01-2020. Accessed 22-09-2020 \[online]. Available at: https://www.geeksforgeeks.org/itertools-groupby-in-python/
4. *numpy.random.randint*, SciPy.org. Accessed 22-09-2020 \[online]. Available at: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
5. *numpy.diagonal*, NumPy.org. Accessed 22-09-2020 \[online]. Available at: https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html